export const mentors = [
  {
    id: 1,
    name: 'Sarah Chen',
    title: 'Senior Software Engineer',
    company: 'Google',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    skills: ['React', 'TypeScript', 'System Design', 'Node.js'],
    rating: 4.9,
    reviews: 47,
    available: true,
    bio: '10+ years building scalable web applications. Passionate about mentoring junior developers.',
  },
  {
    id: 2,
    name: 'Marcus Johnson',
    title: 'Product Manager',
    company: 'Microsoft',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Marcus',
    skills: ['Product Strategy', 'Agile', 'User Research', 'Roadmapping'],
    rating: 4.8,
    reviews: 32,
    available: true,
    bio: 'Led product teams at Fortune 500 companies. Love helping aspiring PMs break into tech.',
  },
  {
    id: 3,
    name: 'Elena Rodriguez',
    title: 'UX Design Lead',
    company: 'Airbnb',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Elena',
    skills: ['UI/UX', 'Figma', 'Design Systems', 'User Testing'],
    rating: 4.7,
    reviews: 28,
    available: true,
    bio: 'Award-winning designer focused on creating delightful user experiences.',
  },
  {
    id: 4,
    name: 'David Kim',
    title: 'Data Scientist',
    company: 'Netflix',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
    skills: ['Python', 'Machine Learning', 'SQL', 'Data Visualization'],
    rating: 4.9,
    reviews: 41,
    available: false,
    bio: 'PhD in ML with industry experience in recommendation systems and analytics.',
  },
  {
    id: 5,
    name: 'Priya Sharma',
    title: 'DevOps Engineer',
    company: 'Amazon',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Priya',
    skills: ['AWS', 'Docker', 'Kubernetes', 'CI/CD'],
    rating: 4.6,
    reviews: 19,
    available: true,
    bio: 'Cloud infrastructure expert helping teams ship faster and more reliably.',
  },
  {
    id: 6,
    name: 'James Wilson',
    title: 'Engineering Manager',
    company: 'Stripe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James',
    skills: ['Leadership', 'Team Building', 'Architecture', 'Mentoring'],
    rating: 4.8,
    reviews: 55,
    available: true,
    bio: 'Former IC turned manager. Focus on career growth and technical leadership.',
  },
];

export const internRequests = [
  {
    id: 1,
    mentorId: 1,
    mentorName: 'Sarah Chen',
    mentorTitle: 'Senior Software Engineer',
    mentorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    message: 'Hi Sarah, I am passionate about frontend development and would love to learn from your experience at Google.',
    status: 'approved',
    sentDate: '2026-05-15',
    responseDate: '2026-05-17',
  },
  {
    id: 2,
    mentorId: 3,
    mentorName: 'Elena Rodriguez',
    mentorTitle: 'UX Design Lead',
    mentorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Elena',
    message: 'I admire your design work at Airbnb and would appreciate guidance on building a design portfolio.',
    status: 'pending',
    sentDate: '2026-06-20',
    responseDate: null,
  },
  {
    id: 3,
    mentorId: 4,
    mentorName: 'David Kim',
    mentorTitle: 'Data Scientist',
    mentorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
    message: 'I am interested in transitioning into data science and would value your mentorship.',
    status: 'rejected',
    sentDate: '2026-04-10',
    responseDate: '2026-04-12',
  },
  {
    id: 4,
    mentorId: 5,
    mentorName: 'Priya Sharma',
    mentorTitle: 'DevOps Engineer',
    mentorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Priya',
    message: 'Looking to learn cloud infrastructure and DevOps best practices from your experience at Amazon.',
    status: 'pending',
    sentDate: '2026-06-25',
    responseDate: null,
  },
];

export const internTasks = [
  {
    id: 1,
    title: 'Build a React Component Library',
    description: 'Create a reusable component library with Button, Input, and Card components using Storybook.',
    priority: 'high',
    assignedBy: 'Sarah Chen',
    dueDate: '2026-07-05',
    status: 'in_progress',
  },
  {
    id: 2,
    title: 'Complete System Design Study',
    description: 'Read and summarize the first 3 chapters of "Designing Data-Intensive Applications".',
    priority: 'medium',
    assignedBy: 'Sarah Chen',
    dueDate: '2026-07-10',
    status: 'pending',
  },
  {
    id: 3,
    title: 'Write Unit Tests for API Endpoints',
    description: 'Achieve 80% test coverage on the user authentication module.',
    priority: 'high',
    assignedBy: 'Sarah Chen',
    dueDate: '2026-06-28',
    status: 'overdue',
  },
  {
    id: 4,
    title: 'Deploy Project to AWS',
    description: 'Set up CI/CD pipeline and deploy the capstone project to AWS using Docker.',
    priority: 'low',
    assignedBy: 'Sarah Chen',
    dueDate: '2026-06-15',
    status: 'completed',
  },
  {
    id: 5,
    title: 'Code Review Practice',
    description: 'Review 3 open-source PRs and write feedback summaries.',
    priority: 'medium',
    assignedBy: 'Sarah Chen',
    dueDate: '2026-07-15',
    status: 'pending',
  },
];

export const internConversations = [
  {
    id: 1,
    name: 'Sarah Chen',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    role: 'Senior Software Engineer',
    online: true,
    unread: 2,
    lastMessage: 'Great progress on the component library!',
    lastMessageTime: '10:30 AM',
    messages: [
      { id: 1, sender: 'Sarah Chen', text: 'Hi! Welcome to the mentorship program. Let me know if you have any questions.', time: '9:00 AM', isOwn: false },
      { id: 2, sender: 'You', text: 'Thank you! I am excited to learn from you.', time: '9:15 AM', isOwn: true },
      { id: 3, sender: 'Sarah Chen', text: 'I reviewed your first task submission. Nice work on the Button component!', time: '10:00 AM', isOwn: false },
      { id: 4, sender: 'You', text: 'Thanks! I added hover states and accessibility attributes.', time: '10:15 AM', isOwn: true },
      { id: 5, sender: 'Sarah Chen', text: 'Great progress on the component library!', time: '10:30 AM', isOwn: false },
    ],
  },
  {
    id: 2,
    name: 'Elena Rodriguez',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Elena',
    role: 'UX Design Lead',
    online: false,
    unread: 0,
    lastMessage: 'Looking forward to our first session!',
    lastMessageTime: 'Yesterday',
    messages: [
      { id: 1, sender: 'You', text: 'Hi Elena, I sent a mentorship request. Hope to hear from you soon!', time: 'Yesterday', isOwn: true },
      { id: 2, sender: 'Elena Rodriguez', text: 'Looking forward to our first session!', time: 'Yesterday', isOwn: false },
    ],
  },
];

export const mentorIncomingRequests = [
  {
    id: 1,
    internId: 101,
    internName: 'Alex Thompson',
    internAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
    field: 'Software Engineering',
    skills: ['JavaScript', 'React', 'CSS'],
    message: 'I am a CS student looking for guidance on breaking into frontend development.',
    status: 'pending',
    sentDate: '2026-06-26',
    responseDate: null,
  },
  {
    id: 2,
    internId: 102,
    internName: 'Maria Garcia',
    internAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Maria',
    field: 'Full Stack Development',
    skills: ['Node.js', 'React', 'MongoDB'],
    message: 'Would love mentorship on building scalable web applications and career advice.',
    status: 'pending',
    sentDate: '2026-06-24',
    responseDate: null,
  },
  {
    id: 3,
    internId: 103,
    internName: 'Jordan Lee',
    internAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jordan',
    field: 'Mobile Development',
    skills: ['React Native', 'Swift', 'Firebase'],
    message: 'Seeking guidance on mobile app architecture and App Store deployment.',
    status: 'accepted',
    sentDate: '2026-06-10',
    responseDate: '2026-06-12',
  },
  {
    id: 4,
    internId: 104,
    internName: 'Sam Patel',
    internAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sam',
    field: 'Backend Engineering',
    skills: ['Python', 'Django', 'PostgreSQL'],
    message: 'Interested in learning system design and backend best practices.',
    status: 'declined',
    sentDate: '2026-05-20',
    responseDate: '2026-05-22',
  },
];

export const assignedInterns = [
  {
    id: 1,
    name: 'Alex Rivera',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AlexR',
    field: 'Frontend Development',
    skills: ['React', 'TypeScript', 'Tailwind CSS'],
    progress: 72,
    tasksCompleted: 8,
    totalTasks: 11,
    status: 'active',
    joinedDate: '2026-03-01',
  },
  {
    id: 2,
    name: 'Taylor Brooks',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Taylor',
    field: 'Full Stack Development',
    skills: ['Node.js', 'React', 'PostgreSQL'],
    progress: 45,
    tasksCompleted: 5,
    totalTasks: 11,
    status: 'active',
    joinedDate: '2026-04-15',
  },
  {
    id: 3,
    name: 'Casey Nguyen',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Casey',
    field: 'Software Engineering',
    skills: ['Java', 'Spring Boot', 'AWS'],
    progress: 90,
    tasksCompleted: 9,
    totalTasks: 10,
    status: 'active',
    joinedDate: '2026-02-10',
  },
  {
    id: 4,
    name: 'Riley Morgan',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Riley',
    field: 'DevOps',
    skills: ['Docker', 'Kubernetes', 'Terraform'],
    progress: 30,
    tasksCompleted: 3,
    totalTasks: 10,
    status: 'inactive',
    joinedDate: '2026-05-01',
  },
];

export const mentorTasks = [
  {
    id: 1,
    title: 'Build REST API with Authentication',
    description: 'Create a RESTful API with JWT authentication and role-based access control.',
    priority: 'high',
    assignee: 'Alex Rivera',
    assigneeId: 1,
    dueDate: '2026-07-08',
    status: 'in_progress',
  },
  {
    id: 2,
    title: 'Implement State Management',
    description: 'Refactor the frontend to use Redux Toolkit for global state management.',
    priority: 'medium',
    assignee: 'Taylor Brooks',
    assigneeId: 2,
    dueDate: '2026-07-12',
    status: 'pending',
  },
  {
    id: 3,
    title: 'Database Schema Design',
    description: 'Design and implement the database schema for the e-commerce platform.',
    priority: 'high',
    assignee: 'Casey Nguyen',
    assigneeId: 3,
    dueDate: '2026-06-25',
    status: 'overdue',
  },
  {
    id: 4,
    title: 'Write Technical Documentation',
    description: 'Document the API endpoints, setup instructions, and architecture decisions.',
    priority: 'low',
    assignee: 'Alex Rivera',
    assigneeId: 1,
    dueDate: '2026-06-20',
    status: 'completed',
  },
  {
    id: 5,
    title: 'Set Up CI/CD Pipeline',
    description: 'Configure GitHub Actions for automated testing and deployment.',
    priority: 'medium',
    assignee: 'Riley Morgan',
    assigneeId: 4,
    dueDate: '2026-07-20',
    status: 'pending',
  },
];

export const mentorConversations = [
  {
    id: 1,
    name: 'Alex Rivera',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AlexR',
    role: 'Frontend Development Intern',
    online: true,
    unread: 1,
    lastMessage: 'I finished the authentication module!',
    lastMessageTime: '11:00 AM',
    messages: [
      { id: 1, sender: 'You', text: 'Hi Alex, welcome! Let\'s start with the REST API task this week.', time: '9:00 AM', isOwn: true },
      { id: 2, sender: 'Alex Rivera', text: 'Sounds great! I\'ll begin with the user model and auth endpoints.', time: '9:30 AM', isOwn: false },
      { id: 3, sender: 'You', text: 'Perfect. Make sure to include refresh token rotation.', time: '10:00 AM', isOwn: true },
      { id: 4, sender: 'Alex Rivera', text: 'I finished the authentication module!', time: '11:00 AM', isOwn: false },
    ],
  },
  {
    id: 2,
    name: 'Taylor Brooks',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Taylor',
    role: 'Full Stack Intern',
    online: false,
    unread: 0,
    lastMessage: 'Can we schedule a code review session?',
    lastMessageTime: 'Yesterday',
    messages: [
      { id: 1, sender: 'Taylor Brooks', text: 'Can we schedule a code review session?', time: 'Yesterday', isOwn: false },
      { id: 2, sender: 'You', text: 'Sure! How about Thursday at 2 PM?', time: 'Yesterday', isOwn: true },
    ],
  },
  {
    id: 3,
    name: 'Casey Nguyen',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Casey',
    role: 'Software Engineering Intern',
    online: true,
    unread: 0,
    lastMessage: 'Database schema is ready for review.',
    lastMessageTime: '2 days ago',
    messages: [
      { id: 1, sender: 'Casey Nguyen', text: 'Database schema is ready for review.', time: '2 days ago', isOwn: false },
      { id: 2, sender: 'You', text: 'I\'ll review it today and send feedback.', time: '2 days ago', isOwn: true },
    ],
  },
];

export const adminUsers = [
  { id: 1, name: 'Alex Rivera', email: 'alex.rivera@email.com', role: 'intern', status: 'active', joinedDate: '2026-03-01', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AlexR' },
  { id: 2, name: 'Sarah Chen', email: 'sarah.chen@email.com', role: 'mentor', status: 'active', joinedDate: '2025-11-15', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah' },
  { id: 3, name: 'Taylor Brooks', email: 'taylor.brooks@email.com', role: 'intern', status: 'active', joinedDate: '2026-04-15', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Taylor' },
  { id: 4, name: 'Marcus Johnson', email: 'marcus.j@email.com', role: 'mentor', status: 'active', joinedDate: '2025-12-01', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Marcus' },
  { id: 5, name: 'Jordan Admin', email: 'jordan.admin@email.com', role: 'admin', status: 'active', joinedDate: '2025-10-01', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jordan' },
  { id: 6, name: 'Sam Patel', email: 'sam.patel@email.com', role: 'intern', status: 'inactive', joinedDate: '2026-01-20', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sam' },
  { id: 7, name: 'Elena Rodriguez', email: 'elena.r@email.com', role: 'mentor', status: 'active', joinedDate: '2026-01-05', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Elena' },
  { id: 8, name: 'Riley Morgan', email: 'riley.m@email.com', role: 'intern', status: 'active', joinedDate: '2026-05-01', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Riley' },
];

export const mentorApplications = [
  {
    id: 1,
    name: 'Chris Anderson',
    email: 'chris.anderson@email.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Chris',
    title: 'Staff Engineer',
    company: 'Meta',
    experience: '12 years',
    skills: ['Distributed Systems', 'Go', 'Kubernetes', 'Leadership'],
    bio: 'Staff engineer with experience leading teams of 20+. Passionate about growing the next generation of engineers.',
    linkedin: 'https://linkedin.com/in/chrisanderson',
    portfolio: 'https://chrisanderson.dev',
    resume: 'https://example.com/resume/chris-anderson.pdf',
    appliedDate: '2026-06-25',
    status: 'pending',
  },
  {
    id: 2,
    name: 'Lisa Wang',
    email: 'lisa.wang@email.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lisa',
    title: 'Design Director',
    company: 'Figma',
    experience: '15 years',
    skills: ['Design Leadership', 'Product Design', 'Design Systems', 'Figma'],
    bio: 'Design leader who has built design teams from scratch at multiple startups.',
    linkedin: 'https://linkedin.com/in/lisawang',
    portfolio: 'https://lisawang.design',
    resume: 'https://example.com/resume/lisa-wang.pdf',
    appliedDate: '2026-06-22',
    status: 'pending',
  },
  {
    id: 3,
    name: 'Robert Taylor',
    email: 'robert.t@email.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Robert',
    title: 'VP of Engineering',
    company: 'Shopify',
    experience: '18 years',
    skills: ['Engineering Leadership', 'Scaling Teams', 'Architecture', 'Strategy'],
    bio: 'VP-level engineering leader with a track record of scaling engineering orgs from 10 to 200+.',
    linkedin: 'https://linkedin.com/in/roberttaylor',
    portfolio: 'https://roberttaylor.io',
    resume: 'https://example.com/resume/robert-taylor.pdf',
    appliedDate: '2026-06-18',
    status: 'pending',
  },
];

export const adminMetrics = {
  totalUsers: 248,
  activePairings: 67,
  pendingApprovals: 3,
  tasksThisMonth: 156,
  roleCounts: { intern: 180, mentor: 62, admin: 6 },
};

export const analyticsData = {
  '7days': {
    signups: 24,
    pairings: 8,
    tasks: 42,
    messages: 318,
    completionRate: 78,
    weeklyActivity: [
      { day: 'Mon', value: 45 },
      { day: 'Tue', value: 62 },
      { day: 'Wed', value: 38 },
      { day: 'Thu', value: 71 },
      { day: 'Fri', value: 55 },
      { day: 'Sat', value: 22 },
      { day: 'Sun', value: 18 },
    ],
    pathways: [
      { name: 'Software Engineering', count: 85, percentage: 42 },
      { name: 'Product Management', count: 38, percentage: 19 },
      { name: 'UX Design', count: 32, percentage: 16 },
      { name: 'Data Science', count: 28, percentage: 14 },
      { name: 'DevOps', count: 18, percentage: 9 },
    ],
  },
  '30days': {
    signups: 89,
    pairings: 34,
    tasks: 156,
    messages: 1247,
    completionRate: 74,
    weeklyActivity: [
      { day: 'W1', value: 180 },
      { day: 'W2', value: 220 },
      { day: 'W3', value: 195 },
      { day: 'W4', value: 245 },
    ],
    pathways: [
      { name: 'Software Engineering', count: 312, percentage: 40 },
      { name: 'Product Management', count: 145, percentage: 19 },
      { name: 'UX Design', count: 128, percentage: 16 },
      { name: 'Data Science', count: 112, percentage: 14 },
      { name: 'DevOps', count: 78, percentage: 10 },
    ],
  },
  '12months': {
    signups: 248,
    pairings: 67,
    tasks: 892,
    messages: 8450,
    completionRate: 71,
    weeklyActivity: [
      { day: 'Jan', value: 420 },
      { day: 'Feb', value: 380 },
      { day: 'Mar', value: 510 },
      { day: 'Apr', value: 470 },
      { day: 'May', value: 590 },
      { day: 'Jun', value: 620 },
      { day: 'Jul', value: 550 },
      { day: 'Aug', value: 480 },
      { day: 'Sep', value: 530 },
      { day: 'Oct', value: 610 },
      { day: 'Nov', value: 570 },
      { day: 'Dec', value: 490 },
    ],
    pathways: [
      { name: 'Software Engineering', count: 980, percentage: 38 },
      { name: 'Product Management', count: 520, percentage: 20 },
      { name: 'UX Design', count: 410, percentage: 16 },
      { name: 'Data Science', count: 380, percentage: 15 },
      { name: 'DevOps', count: 290, percentage: 11 },
    ],
  },
};

export const allSkills = [
  'React', 'TypeScript', 'Node.js', 'Python', 'Java', 'AWS',
  'Docker', 'Kubernetes', 'UI/UX', 'Figma', 'Product Strategy',
  'Machine Learning', 'SQL', 'Leadership', 'System Design', 'CI/CD',
];
